//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S00213942ProjectOOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frame : IComparable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Frame()
        {
            this.Forks = new HashSet<Fork>();
            this.Drivetrains = new HashSet<Drivetrain>();
        }
    
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Discipline { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string FrameImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fork> Forks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drivetrain> Drivetrains { get; set; }

        public int CompareTo(object obj)
        {
            Frame otherframe = obj as Frame;

            return this.Brand.CompareTo(otherframe.Brand);
        }

        internal string GetDetails()
        {
            throw new NotImplementedException();
        }
    }
}
